import React from 'react';
import { render } from 'react-dom';
import { BrowserRouter, Switch , Route } from 'react-router-dom'

import ProductsList from './onlineshop/productslist.jsx';
import NavigationBar from './onlineshop/navigationbar.jsx';
import SelectedProduct from './onlineshop/selectedproduct.jsx';
import AddImage from './onlineshop/addimage.jsx';
import EditProduct from './onlineshop/editproduct.jsx';
import DeleteProduct from './onlineshop/deleteproduct.jsx';

//  compile command at command line :  ./node_modules/.bin/webpack -d
// check bundle.js file for updates ( autogenerated javascript file for production )

class App extends React.Component {

	render() {
	
		return (
			<BrowserRouter>
				<Switch>
					<Route exact path="/" component={ProductsList} />
					<Route path="/product/:productUUID" component={SelectedProduct} />
					<Route path="/productimage/:productUUID" component={AddImage} />
					<Route path="/editproduct/:productUUID" component={EditProduct} />
					<Route path="/deleteproduct/:productUUID" component={DeleteProduct} />
				</Switch>
			</BrowserRouter>
		);
		
	}

}

render(<App />, document.getElementById('app'));

